// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleIntelligence.Infrastructure.Persistence;

#nullable disable

namespace VehicleIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(VehicleIntelligenceDbContext))]
    [Migration("20260705121958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TelemetryRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Alerts_CreatedAt");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_Alerts_IsResolved");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_Alerts_Severity");

                    b.HasIndex("TelemetryRecordId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_Alerts_VehicleId");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BatteryCurrent")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyConsumption")
                        .HasColumnType("double precision");

                    b.Property<double?>("EngineLoad")
                        .HasColumnType("double precision");

                    b.Property<double?>("EngineRpm")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuelRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("text");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TripId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_TelemetryRecords_Timestamp");

                    b.HasIndex("VehicleId", "Timestamp")
                        .HasDatabaseName("IX_TelemetryRecords_VehicleId_Timestamp");

                    b.ToTable("TelemetryRecords", (string)null);
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Vehicles_ExternalId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.Alert", b =>
                {
                    b.HasOne("VehicleIntelligence.Domain.Entities.TelemetryRecord", "TelemetryRecord")
                        .WithMany("Alerts")
                        .HasForeignKey("TelemetryRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VehicleIntelligence.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Alerts")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelemetryRecord");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.TelemetryRecord", b =>
                {
                    b.HasOne("VehicleIntelligence.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.TelemetryRecord", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("VehicleIntelligence.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("TelemetryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
