using VehicleIntelligence.Domain.Common;
using VehicleIntelligence.Domain.Enums;

namespace VehicleIntelligence.Domain.Entities;

/// <summary>
/// Represents an anomaly alert generated by the rule engine for a vehicle.
/// </summary>
public class Alert : BaseEntity
{
    public Guid VehicleId { get; private set; }

    public Guid? TelemetryRecordId { get; private set; }

    public AlertType AlertType { get; private set; }

    public AlertSeverity Severity { get; private set; }

    public string Message { get; private set; } = string.Empty;

    public double RiskScore { get; private set; }

    public bool IsResolved { get; private set; }

    public DateTime? ResolvedAt { get; private set; }

    // Navigation
    public Vehicle Vehicle { get; private set; } = null!;
    public TelemetryRecord? TelemetryRecord { get; private set; }

    private Alert() { }

    public static Alert Create(
        Guid vehicleId,
        AlertType alertType,
        AlertSeverity severity,
        string message,
        double riskScore,
        Guid? telemetryRecordId = null)
    {
        return new Alert
        {
            VehicleId = vehicleId,
            TelemetryRecordId = telemetryRecordId,
            AlertType = alertType,
            Severity = severity,
            Message = message,
            RiskScore = Math.Clamp(riskScore, 0, 100),
            IsResolved = false
        };
    }

    public void Resolve()
    {
        if (IsResolved) return;
        IsResolved = true;
        ResolvedAt = DateTime.UtcNow;
    }
}
